# Generated by Django 2.2 on 2019-05-16 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splash', '0001_initial'),
    ]

    operations = [
         migrations.RenameModel('Words', 'Wordlist')
    ]
